/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}', './projects/**/*.{html,ts}'],
  daisyui: {
    themes: ['light'],
  },
  theme: {
    extend: {
      colors: {
        primary: 'var(--color-primary, #12372A)',
        secondary: 'var(--color-secondary, #436850)',
        tertiary: 'var(--color-tertiary, #ADBC9F)',
        quaternary: 'var(--color-quaternary, #FBFADA)',
        accent: {
          neon: 'var(--color-accent-neon, #FF6B35)',
          purple: 'var(--color-accent-purple, #8B5FBF)',
          lime: 'var(--color-accent-lime, #39FF14)',
        },
        glass: {
          50: 'var(--color-glass-50, rgba(255, 255, 255, 0.05))',
          100: 'var(--color-glass-100, rgba(255, 255, 255, 0.10))',
          200: 'var(--color-glass-200, rgba(255, 255, 255, 0.15))',
        },
        surface: {
          primary: 'var(--color-surface-primary, #ffffff)',
          secondary: 'var(--color-surface-secondary, #f8fafc)',
          tertiary: 'var(--color-surface-tertiary, #f1f5f9)',
        },
        text: {
          primary: 'var(--color-text-primary, #1e293b)',
          secondary: 'var(--color-text-secondary, #475569)',
          tertiary: 'var(--color-text-tertiary, #64748b)',
          inverse: 'var(--color-text-inverse, #ffffff)',
        },
        border: {
          primary: 'var(--color-border-primary, #e2e8f0)',
          secondary: 'var(--color-border-secondary, #cbd5e1)',
          accent: 'var(--color-border-accent, #12372A)',
        },
      },
      spacing: {
        'token-xs': 'var(--spacing-xs, 0.25rem)',
        'token-sm': 'var(--spacing-sm, 0.5rem)',
        'token-md': 'var(--spacing-md, 1rem)',
        'token-lg': 'var(--spacing-lg, 1.5rem)',
        'token-xl': 'var(--spacing-xl, 2rem)',
        'token-2xl': 'var(--spacing-2xl, 3rem)',
        'token-3xl': 'var(--spacing-3xl, 4rem)',
        'token-4xl': 'var(--spacing-4xl, 6rem)',
        'token-5xl': 'var(--spacing-5xl, 8rem)',
        'component-xs': 'var(--component-spacing-xs, 0.5rem)',
        'component-sm': 'var(--component-spacing-sm, 0.75rem)',
        'component-md': 'var(--component-spacing-md, 1rem)',
        'component-lg': 'var(--component-spacing-lg, 1.5rem)',
        'component-xl': 'var(--component-spacing-xl, 2rem)',
        'layout-section': 'var(--layout-spacing-section, 3rem)',
        'layout-container': 'var(--layout-spacing-container, 1rem)',
        'layout-gutter': 'var(--layout-spacing-gutter, 1.5rem)',
      },
      fontSize: {
        'token-xs': ['var(--font-size-xs, 0.75rem)', { lineHeight: 'var(--line-height-4, 1rem)' }],
        'token-sm': ['var(--font-size-sm, 0.875rem)', { lineHeight: 'var(--line-height-5, 1.25rem)' }],
        'token-base': ['var(--font-size-base, 1rem)', { lineHeight: 'var(--line-height-6, 1.5rem)' }],
        'token-lg': ['var(--font-size-lg, 1.125rem)', { lineHeight: 'var(--line-height-7, 1.75rem)' }],
        'token-xl': ['var(--font-size-xl, 1.25rem)', { lineHeight: 'var(--line-height-7, 1.75rem)' }],
        'token-2xl': ['var(--font-size-2xl, 1.5rem)', { lineHeight: 'var(--line-height-8, 2rem)' }],
        'token-3xl': ['var(--font-size-3xl, 1.875rem)', { lineHeight: 'var(--line-height-9, 2.25rem)' }],
        'token-4xl': ['var(--font-size-4xl, 2.25rem)', { lineHeight: 'var(--line-height-10, 2.5rem)' }],
      },
      fontWeight: {
        'token-thin': 'var(--font-weight-thin, 100)',
        'token-light': 'var(--font-weight-light, 300)',
        'token-normal': 'var(--font-weight-normal, 400)',
        'token-medium': 'var(--font-weight-medium, 500)',
        'token-semibold': 'var(--font-weight-semibold, 600)',
        'token-bold': 'var(--font-weight-bold, 700)',
        'token-extrabold': 'var(--font-weight-extrabold, 800)',
      },
      borderRadius: {
        'token-sm': 'var(--border-radius-sm, 0.125rem)',
        'token': 'var(--border-radius-base, 0.25rem)',
        'token-md': 'var(--border-radius-md, 0.375rem)',
        'token-lg': 'var(--border-radius-lg, 0.5rem)',
        'token-xl': 'var(--border-radius-xl, 0.75rem)',
        'token-2xl': 'var(--border-radius-2xl, 1rem)',
        'token-3xl': 'var(--border-radius-3xl, 1.5rem)',
        'token-full': 'var(--border-radius-full, 9999px)',
      },
      boxShadow: {
        'token-sm': 'var(--shadow-sm, 0 1px 2px 0 rgb(0 0 0 / 0.05))',
        'token': 'var(--shadow-base, 0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1))',
        'token-md': 'var(--shadow-md, 0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1))',
        'token-lg': 'var(--shadow-lg, 0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1))',
        'token-xl': 'var(--shadow-xl, 0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1))',
        'token-2xl': 'var(--shadow-2xl, 0 25px 50px -12px rgb(0 0 0 / 0.25))',
      },
      transitionDuration: {
        'token-fast': 'var(--duration-fast, 150ms)',
        'token-normal': 'var(--duration-normal, 300ms)',
        'token-slow': 'var(--duration-slow, 500ms)',
        'token-slower': 'var(--duration-slower, 700ms)',
      },
      transitionTimingFunction: {
        'token-smooth': 'var(--easing-smooth, cubic-bezier(0.4, 0, 0.2, 1))',
        'token-bounce': 'var(--easing-bounce, cubic-bezier(0.68, -0.55, 0.265, 1.55))',
      },
      animation: {
        'fade-in': 'fade-in var(--duration-slow, 0.5s) var(--easing-out, ease-out)',
        'scale-in': 'scale-in var(--duration-normal, 0.3s) var(--easing-out, ease-out)',
        'bounce-slow': 'bounce-slow 3s ease-in-out infinite',
        'token-fade-in': 'fade-in var(--duration-slow, 0.5s) var(--easing-out, ease-out)',
        'token-scale-in': 'scale-in var(--duration-normal, 0.3s) var(--easing-out, ease-out)',
      },
      keyframes: {
        'fade-in': {
          from: { opacity: '0', transform: 'translateY(20px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'scale-in': {
          from: { opacity: '0', transform: 'scale(0.9)' },
          to: { opacity: '1', transform: 'scale(1)' },
        },
        'bounce-slow': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-20px)' },
        },
      },
      perspective: {
        1000: 'var(--perspective-1000, 1000px)',
      },
      backdropBlur: {
        'token-md': 'var(--backdrop-blur-md, 12px)',
        'token-xl': 'var(--backdrop-blur-xl, 24px)',
      },
      zIndex: {
        'dropdown': 'var(--z-index-dropdown, 1000)',
        'sticky': 'var(--z-index-sticky, 1020)',
        'fixed': 'var(--z-index-fixed, 1030)',
        'modal-backdrop': 'var(--z-index-modal-backdrop, 1040)',
        'modal': 'var(--z-index-modal, 1050)',
        'popover': 'var(--z-index-popover, 1060)',
        'tooltip': 'var(--z-index-tooltip, 1070)',
        'toast': 'var(--z-index-toast, 1080)',
      },
    },
  },
  plugins: [require('daisyui')],
};
