name: Deploy Angular Blog to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Generate Angular environment files
        run: |
          cat <<EOF > src/environments/environment.ts
          export const environment = {
            production: false,
            supabaseUrl: '${SUPABASE_URL}',
            supabaseKey: '${SUPABASE_ANON_KEY}',
          };
          EOF
          cat <<EOF > src/environments/environment.prod.ts
          export const environment = {
            production: true,
            supabaseUrl: '${SUPABASE_URL}',
            supabaseKey: '${SUPABASE_ANON_KEY}',
          };
          EOF
           cat <<EOF > src/environments/environment.development.ts
          export const environment = {
            production: true,
            supabaseUrl: '${SUPABASE_URL}',
            supabaseKey: '${SUPABASE_ANON_KEY}',
          };
          EOF
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

      - run: npm ci

      - run: npm run test -- --browsers=ChromeHeadless --watch=false --no-progress

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Generate Angular environment files
        run: |
          cat <<EOF > src/environments/environment.ts
          export const environment = {
            production: false,
            supabaseUrl: '${SUPABASE_URL}',
            supabaseKey: '${SUPABASE_ANON_KEY}',
          };
          EOF
          cat <<EOF > src/environments/environment.prod.ts
          export const environment = {
            production: true,
            supabaseUrl: '${SUPABASE_URL}',
            supabaseKey: '${SUPABASE_ANON_KEY}',
          };
          EOF
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

      - run: npm ci

      - run: npm run build --prod

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Install Google Cloud SDK
        run: |
          echo "Installing Google Cloud SDK"
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          sudo apt-get install -y apt-transport-https ca-certificates
          sudo apt-get update && sudo apt-get install -y google-cloud-sdk
          gcloud version

      - name: Deploy to Cloud Run using Buildpacks
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: angular-blog
          region: europe-west4
          source: .
